server:
  port: 8081
spring:
  application:
    name: protobuf
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    default-property-inclusion: non_null

logging:
  config: classpath:logback-spring.xml
  path: logs/